# Generated by Django 4.2.3 on 2023-07-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_lecturers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturers',
            new_name='Lecturer',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
