# Generated by Django 4.2.3 on 2023-08-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_classsession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
