# Generated by Django 4.2.3 on 2023-08-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_classsession_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='8:00am - 10:00am', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='Lecture', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.CharField(default='UG', max_length=100),
        ),
    ]
