# Generated by Django 4.2.3 on 2023-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_course_remove_lecturer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(max_length=300),
        ),
    ]
