# Generated by Django 4.2.3 on 2023-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_description_course_time_course_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(to='base.course', verbose_name='courses registered'),
        ),
    ]
